version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  # Example of how to add a database if needed later
  # db:
  #   image: postgres:15-alpine
  #   container_name: discord-bot-db
  #   restart: unless-stopped
  #   env_file:
  #     - .env.db
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data: